apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bot-commerce-backend
  title: Bot Commerce Backend Service
  description: Serviço backend principal em FastAPI responsável por orquestrar o fluxo de atendimento, endpoints REST e servir o widget de chat.
  tags:
    - python
    - fastapi
    - backend
    - uvicorn
    - chatbot
  annotations:
    backstage.io/source-location: url:https://github.com/EUbrener/bot-commerce/tree/main/app
spec:
  type: service
  lifecycle: development
  owner: user:default/brener
  system: bot-commerce-system
  providesApis:
    - bot-commerce-api
  dependsOn:
    - component:default/bot-commerce-nlp-engine
