apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: bot-commerce
  title: bot-commerce
  description: Sistema bot-commerce analisado automaticamente
  annotations:
    github.com/project-slug: EUbrener/bot-commerce
spec:
  owner: user:Brenolla
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: bot-commerce-docs
  title: bot-commerce-docs
  description: API bot-commerce-docs (openapi)
  annotations:
    github.com/project-slug: EUbrener/bot-commerce
spec:
  type: openapi
  lifecycle: experimental
  owner: user:Brenolla
  system: bot-commerce
  definition:
    $text: ./worker/docs/openapi.yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bot-commerce
  title: bot-commerce
  description: Componente bot-commerce (service)
  tags:
  - python
  - fastapi
  annotations:
    github.com/project-slug: EUbrener/bot-commerce
spec:
  type: service
  lifecycle: experimental
  owner: user:Brenolla
  system: bot-commerce
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bot-commerce-frontend
  title: bot-commerce-frontend
  description: Componente bot-commerce-frontend (website)
  tags:
  - node
  - react
  - vite
  annotations:
    github.com/project-slug: EUbrener/bot-commerce
spec:
  type: website
  lifecycle: experimental
  owner: user:Brenolla
  system: bot-commerce

